openapi: 3.1.0
info:
  title: MeshPlay-Lab Gateway API
  version: 0.0.1
  description: REST API documentation for the MeshPlay-Lab Gateway Service.
servers:
  - url: 'http://localhost:5000/api'
    description: Local development server
tags:
  - name: Auth
    description: User authentication and session management
  - name: User
    description: User manipulation logic
paths:
  /auth/signup:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: test_user
                password:
                  type: string
                  example: Passw0rd!
      responses:
        '201':
          description: Signup success (signup)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User signed up successfully
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        pattern: '^[0-9]+$'
                        example: '42'
                      username:
                        type: string
                        example: johndoe
                      createdAt:
                        type: string
                        format: date-time
                        example: '2025-11-12T22:41:51.540Z'
                      lastLogin:
                        type: string
                        format: date-time
                        example: '2025-11-16T22:41:51.540Z'
                    required:
                      - id
                      - username
                  meta:
                    $ref: '#/paths/~1auth~1login/post/responses/200/content/application~1json/schema/properties/meta'
                required:
                  - success
                  - message
                  - data
        '400':
          $ref: '#/paths/~1auth~1login/post/responses/400'
        '409':
          description: The provided username is already taken.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/400/content/application~1json/schema'
              examples:
                userExists:
                  summary: Duplicate username
                  value:
                    success: false
                    message: User already exists
                    error:
                      code: USER_EXISTS
                      details: []
          x-errorCodes:
            - USER_EXISTS
        '500':
          $ref: '#/paths/~1auth~1login/post/responses/500'
  /auth/login:
    post:
      summary: Authenticate and return token
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: test_user
                password:
                  type: string
                  example: Passw0rd!
      responses:
        '200':
          description: Authentication success (login)
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User authenticated successfully
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                    required:
                      - token
                  meta:
                    type: object
                    properties:
                      requestId:
                        type: string
                      timestamp:
                        type: string
                        format: date-time
                required:
                  - success
                  - message
                  - data
        '400':
          description: The request could not be understood due to malformed syntax or invalid input.
          content:
            application/json:
              schema:
                description: Standard error response envelope
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                        message:
                          type: string
                          example: Invalid request parameters
                        error:
                          type: object
                          properties:
                            code:
                              $ref: '#/error%20codes/ErrorCodes/ErrorCode'
                            details:
                              type: array
                              items:
                                type: string
                              example:
                                - username is required
                        meta:
                          $ref: '#/paths/~1auth~1login/post/responses/200/content/application~1json/schema/properties/meta'
                      required:
                        - success
                        - message
                        - error
              examples:
                invalidJson:
                  summary: Invalid or malformed JSON
                  value:
                    success: false
                    message: Invalid JSON in request body
                    error:
                      code: BAD_REQUEST
                      details:
                        - Unexpected token in JSON at position 12
          x-errorCodes:
            - BAD_REQUEST
            - VALIDATION_ERROR
        '401':
          description: Login failed due to invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/400/content/application~1json/schema'
              examples:
                invalidCredentials:
                  summary: Invalid username or password
                  value:
                    success: false
                    message: Invalid username or password
                    error:
                      code: INVALID_CREDENTIALS
          x-errorCodes:
            - INVALID_CREDENTIALS
        '500':
          description: An unexpected server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/400/content/application~1json/schema'
              examples:
                internalServerError:
                  summary: Database or internal failure
                  value:
                    success: false
                    message: Unexpected server error
                    error:
                      code: INTERNAL_ERROR
                      details:
                        - Unhandled exception in auth service
          x-errorCodes:
            - INTERNAL_ERROR
  '/auth/user/{id}/get':
    get:
      summary: Get a user by ID
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: Numeric ID of the user to retrieve
          schema:
            type: string
            pattern: '^[0-9]+$'
          examples:
            validId:
              value: '42'
      responses:
        '200':
          description: 'User retrieved successfully (/user/{id}/get)'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: User retrieved successfully
                  data:
                    $ref: '#/paths/~1auth~1signup/post/responses/201/content/application~1json/schema/properties/data'
                  meta:
                    $ref: '#/paths/~1auth~1login/post/responses/200/content/application~1json/schema/properties/meta'
                required:
                  - success
                  - message
                  - data
        '400':
          $ref: '#/paths/~1auth~1login/post/responses/400'
        '401':
          description: Authentication is required or the provided credentials are invalid.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/400/content/application~1json/schema'
              examples:
                missingAuthHeader:
                  summary: Missing Authorization header
                  value:
                    success: false
                    message: Missing Authorization header
                    error:
                      code: MISSING_AUTH_HEADER
                invalidJwt:
                  summary: Invalid JWT
                  value:
                    success: false
                    message: The provided JWT token is invalid or expired
                    error:
                      code: INVALID_JWT
          x-errorCodes:
            - MISSING_AUTH_HEADER
            - INVALID_JWT
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/paths/~1auth~1login/post/responses/400/content/application~1json/schema'
              examples:
                invalidCredentials:
                  summary: User not found
                  value:
                    success: false
                    message: Could not find requested user
                    error:
                      code: USER_NOT_FOUND
          x-errorCodes:
            - USER_NOT_FOUND
        '500':
          $ref: '#/paths/~1auth~1login/post/responses/500'
error codes:
  ErrorCodes:
    ErrorCode:
      type: string
      description: |
        Machine-readable error codes returned by the MeshPlay-Lab API.
        These codes appear in the `error.code` field of error responses and
        allow clients to programmatically handle specific error conditions.
      enum:
        - MISSING_AUTH_HEADER
        - MISSING_JWT
        - EXPIRED_JWT
        - INVALID_JWT
        - INVALID_JWT_FORMAT
        - INVALID_JWT_CONTENT
        - INVALID_CREDENTIALS
        - USER_EXISTS
        - USER_NOT_FOUND
        - BAD_REQUEST
        - VALIDATION_ERROR
        - UNAUTHORIZED
        - DB_ERROR
        - DUPLICATE_ENTRY
        - INTERNAL_ERROR
        - CONFLICT_ERROR
        - NOT_FOUND
      example: VALIDATION_ERROR
    ErrorCodeDescriptions:
      type: object
      description: Human-readable descriptions for all error codes.
      properties:
        MISSING_AUTH_HEADER:
          type: string
          example: The 'Authorization' header was missing from the request.
        MISSING_JWT:
          type: string
          example: The JWT token was not provided in the 'Authorization' header.
        EXPIRED_JWT:
          type: string
          example: The provided JWT token has expired.
        INVALID_JWT:
          type: string
          example: The JWT token could not be verified or is invalid.
        INVALID_JWT_FORMAT:
          type: string
          example: The JWT format is incorrect or missing segments.
        INVALID_JWT_CONTENT:
          type: string
          example: The JWT payload contains invalid or missing claims.
        INVALID_CREDENTIALS:
          type: string
          example: Invalid username or password provided during login.
        USER_EXISTS:
          type: string
          example: A user with the provided username already exists.
        USER_NOT_FOUND:
          type: string
          example: No user matching the provided identifier was found.
        BAD_REQUEST:
          type: string
          example: The request was malformed or contained invalid parameters.
        VALIDATION_ERROR:
          type: string
          example: The request body failed validation checks.
        UNAUTHORIZED:
          type: string
          example: The user is not authorized to access this resource.
        DB_ERROR:
          type: string
          example: A database operation failed unexpectedly.
        DUPLICATE_ENTRY:
          type: string
          example: A record with the same unique value already exists.
        INTERNAL_ERROR:
          type: string
          example: An unexpected internal server error occurred.
        CONFLICT_ERROR:
          type: string
          example: The request could not be completed due to a resource conflict.
        NOT_FOUND:
          type: string
          example: The requested resource could not be found.
